server:
  port: 8090

spring:
  application:
    name: Clients App
  datasource:
    url: jdbc:postgresql://localhost:5442/clients
    username: clients
    password: clients
    driverClassName: org.postgresql.Driver
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
    initialization-mode: always
#    data:
#      - classpath:clients.sql
  jpa:
    open-in-view: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      properties:
        format-sql: true

security:
  jwt:
    signing-key: e152d009ecbb27f83d7545bfe2f246c0c5ffc253f57b4a05229a54beb68c21c3
#  oauth2:
#    client:
#      client-id: "ddc87e63-4ef1-4a0e-bf98-29595d1912c8"
#      client-secret: "041bcbc6-091d-4c5e-a031-8c4d8f1a2a1d"
#      scope: password
