server:
  port: 8090

spring:
  application:
    name: Clients App
  datasource:
    url: jdbc:h2:mem:clients
    driverClassName: org.h2.Driver
    username: clients
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
