server:
  port: 8090

spring:
  application:
    name: Clients App
  datasource:
    url: jdbc:postgresql://localhost:5442/clients
    username: clients
    password: clients
    driverClassName: org.postgresql.Driver
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
    initialization-mode: always
    data:
      - classpath:clients.sql
  jpa:
    open-in-view: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
      properties:
        format-sql: true
